// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbezVg3iesurAgaDPPCsrNq6gMylPcNE0',
    appId: '1:935560579206:web:725b290bc4bdf74fc42907',
    messagingSenderId: '935560579206',
    projectId: 'ai-course-project-455ed',
    authDomain: 'ai-course-project-455ed.firebaseapp.com',
    storageBucket: 'ai-course-project-455ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ5a9iQZoJARC7wpizGaAw7_AjqnA8WLo',
    appId: '1:935560579206:android:35e82c89c7006d79c42907',
    messagingSenderId: '935560579206',
    projectId: 'ai-course-project-455ed',
    storageBucket: 'ai-course-project-455ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFQuH6fVeYDAwIZzbBjtVYFg2B3X1pu8Y',
    appId: '1:935560579206:ios:4c27572b504e6313c42907',
    messagingSenderId: '935560579206',
    projectId: 'ai-course-project-455ed',
    storageBucket: 'ai-course-project-455ed.appspot.com',
    iosClientId: '935560579206-u5tjmhmn0k0q29vldvf59pu4ipejkpc1.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiwebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFQuH6fVeYDAwIZzbBjtVYFg2B3X1pu8Y',
    appId: '1:935560579206:ios:89805b2892c82af2c42907',
    messagingSenderId: '935560579206',
    projectId: 'ai-course-project-455ed',
    storageBucket: 'ai-course-project-455ed.appspot.com',
    iosClientId: '935560579206-ph3qpsh96de6ooog3b55q3mdihaopfss.apps.googleusercontent.com',
    iosBundleId: 'dfsa',
  );
}
